[package]
name = "potinv_api"
version = "0.1.0"
authors = ["rhay <me@russellhay.com>"]
edition = "2018"
publish = false

[dependencies]
potinv_domain = { path = "../potinv_domain" }
juniper = "0.14"
juniper_warp = "0.5"
minimal-id = { version = "0.8", features = ["juniper", "graphql"] }
